---
output:
  xaringan::moon_reader:
    chakra: libs/remark-latest.min.js
    css: "my-theme.css"
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
---

```{r setup, include=FALSE, message=FALSE}
options(htmltools.dir.version = FALSE, servr.daemon = TRUE)
```

class: center, middle

# RESEARCH UPDATE SUMMARY
## Assistant Unit Leader
### Washington Cooperative Fish and Wildlife Research Unit
### Annual Business Meeting
### 21 Oct 2020

---

class: center, middle

# PROJECTS ENDING IN 2020

---

.blue-text[
## Improving preseason forecasts for U.S. coho salmon management units by accounting for spatially structured temporal variation in age-at-maturity
]

***

### Lukas DeFilippo (Ph.D. student, UW)
### Daniel Schindler (co-PI, UW-SAFS)
### Neala Kendall (co-PI, WDFW)
### Thomas Buehrens (WDFW)

---

.blue-text[
## Improving preseason forecasts for U.S. coho salmon management units by accounting for spatially structured temporal variation in age-at-maturity
]

***

### .green-text[Funder:] Southern Boundary Restoration and Enhancement Fund

### .green-text[Status:] Ongoing, expected completion in October 2020

* ### Develop forecast models for naturally spawning coho salmon that account for both environmental and demographic effects on the proportion of jacks within cohorts

* ### Paper in final stages of revision; webinar on October 26

---

class: center, middle

# ONGOING PROJECTS

---

.blue-text[
## A comparison of existing and spatio-temporal methods to apportion coastwide catch limits for subregional management in the Gulf of Alaska
]

***

### Kelly Mistry (MS student)
### Cecilia O'Leary (co-PI, NOAA Fisheries)

---

.blue-text[
## A comparison of existing and spatio-temporal methods to apportion coastwide catch limits for subregional management in the Gulf of Alaska
]

***

### .green-text[Funders:] NOAA Fisheries

### .green-text[Status:] Ongoing; expected completion in April 2022

* ### Develop the alternative approaches for subregional groundfish harvest apportionment for Gulf of Alaska stocks

* ###	Compare the performance of conventional and alternative approaches to inform fisheries management councils


---

.blue-text[
## Evaluation of status and trends for Skagit River Chinook salmon
]

***

### Mike LeMoine (co-PI, Skagit River System Cooperative)
### Casey Ruff (co-PI, Skagit River System Cooperative)
### Eric Beamer (co-PI, Skagit River System Cooperative)

---

.blue-text[
## Evaluation of status and trends for Skagit River Chinook salmon
]

***

### .green-text[Funders:] Bureau of Indian Affairs, University of Washington

### .green-text[Status:] Ongoing; expected completion in June 2021

* ### Develop integrated population model to evaluate current status and trends in population censuses of Chinook salmon

* ### Revise methods for estimating escapement from index stocks based on coded wire tagging of hatchery fish and test fisheries


---

class: center, middle

# PROJECTS IN DEVELOPMENT

---

.blue-text[
## 5-year status assessment for Puget Sound rockfish
]

***

### Markus Min (MS student)
### Dan Tonnes (NOAA Fisheries)
### Jason Cope (NOAA Fisheries)
### Bob Pacunski (WDFW)

---

.blue-text[
## 5-year status assessment for Puget Sound rockfish
]

***

### .green-text[Funders:] NOAA Fisheries

### .green-text[Status:] Expected to begin in January 2021

* ### Update status assessment for ESA-listed rockfish in Puget Sound


---

.blue-text[
## Habitat function of shellfish aquaculture ecosystems
]

***

### Karl Veggerby (MS student)
### Beth Sanderson (Co-PI, NOAA Fisheries)
### Bridgett Ferris (Co-PI, NOAA Fisheries)

---

.blue-text[
## Habitat function of shellfish aquaculture ecosystems
]

***

### .green-text[Funders:] NOAA Fisheries

### .green-text[Status:] Expected to begin in January 2021

* ### Quantify occurrences of foraging behavior, by species, in Manila clam, Pacific oyster on-bottom, and Pacific oyster off-bottom aquaculture sites using underwater video

* ### Characterize crab and fish feeding in aquaculture and reference habitats using diets and stable isotopes

---

.blue-text[
## Advancing sustainable shellfish aquaculture through machine learning and automated data collection on fish communities
]

***

### Dara Farrell (Post-doc)
### Beth Sanderson (Co-PI, NOAA Fisheries)
### Bridgett Ferris (Co-PI, NOAA Fisheries)

---

.blue-text[
## Advancing sustainable shellfish aquaculture through machine learning and automated data collection on fish communities
]

***

### .green-text[Funders:] NOAA Fisheries

### .green-text[Status:] Expected to begin in January 2021

* ### Transition an existing machine learning model to the NOAA-supported VIAME platform

* ### Test and assess model’s limitations, write documentation, and areas for future development

---

.blue-text[
## Investigating how the dispersal of fry and distribution of redds interact to shape density-dependence and productive capacity in Skagit River steelhead
]

***

### Nick Chambers (MS student)
### Daniel Schindler (Co-PI, UW-SAFS)
### George Pess (NOAA Fisheries)
### Joe Anderson (WDFW)
### John McMillan (Trout Unlimited)

---

.blue-text[
## Investigating how the dispersal of fry and distribution of redds interact to shape density-dependence and productive capacity in Skagit River steelhead
]

***

### .green-text[Funders:] NOAA Fisheries, Seattle City Light

### .green-text[Status:] Expected to begin in January 2021

* ### Quantify the distribution of steelhead redds and estimate dispersal distance of fry in portions of the mainstem Skagit River

* ### Determine the types of habitat conditions that fry prefer and estimate the overall amount of that habitat that is available in the mainstem Skagit River

---

.blue-text[
## Assessing population viability for species of greatest conservation need in the Pacific Northwest
]

***

### Nicole Doran (MS student)
### Jim Unsworth (USFWS)
### Brad Thompson (USFWS)

---

.blue-text[
## Assessing population viability for species of greatest conservation need in the Pacific Northwest
]

***

### .green-text[Funders:] USFWS

### .green-text[Status:] Expected to begin in September 2021

* ### Assess how habitat loss, fragmentation, and modification combine with direct human influences to negatively affect the viability of *species of greatest concern* in the Pacific Northwest

---

class: black-back

