---
output:
  xaringan::moon_reader:
    chakra: libs/remark-latest.min.js
    css: "my-theme.css"
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
---

```{r setup, include=FALSE, message=FALSE}
options(htmltools.dir.version = FALSE, servr.daemon = TRUE)
```

class: center, middle

# RESEARCH UPDATE SUMMARY
## Assistant Unit Leader
### Cooperator's Meeting, 23 Oct 2019

.purple-text.center[
.futnote[`r icon::fa("envelope")` scheuerl@uw.edu]
]

.blue-text.center[
.citation[`r icon::fa("twitter")` @mark_scheuerell]
]

---

.blue-text[
## Improving preseason forecasts for U.S. coho salmon management units by accounting for spatially structured temporal variation in age-at-maturity
]

***

### Lukas DeFilippo (Ph.D. student, University of Washington)
### Daniel Schindler (co-PI, University of Washington)
### Neala Kendall (co-PI, Washington Department of Fish and Wildlife)
### Thomas Buehrens (Washington Department of Fish and Wildlife)

---

.blue-text[
## Improving preseason forecasts for U.S. coho salmon management units by accounting for spatially structured temporal variation in age-at-maturity
]

***

### .green-text[Funder:] Southern Boundary Restoration and Enhancement Fund

### .green-text[Status:] Ongoing, expected completion March 2020

* ### Develop forecast models for naturally spawning coho salmon that accounts for both environmental and demographic effects on the proportion of jacks within cohorts

---

.blue-text[
## Non-market economic benefits of restoration of Oregon Coast coho salmon
]

***

### Caitlin Magel (Ph.D. student, Oregon State University)
### Sally Hacker (co-PI, Oregon State University) 
### Eric Buhle (BioMark, Inc)
### David Lewis (co-PI, Oregon State University)

---

.blue-text[
## Non-market economic benefits of restoration of Oregon Coast coho salmon
]

***

### .green-text[Funders:] National Oceanic and Atmospheric Administration, National Science Foundation

### .green-text[Status:] Ongoing, expected completion June 2020

* ### Develop an integrated population model that translates habitat investments to returning coho spawners

* ### Link survey-based valuation estimates to potential changes in the number of coho spawners arising from restoration actions


---

.blue-text[
## Evaluation of status and trends for Skagit River Chinook salmon and steelhead
]

***

### Eric Beamer (co-PI, Skagit River System Cooperative)
### Mike LeMoine (co-PI, Skagit River System Cooperative)
### Casey Ruff (co-PI, Skagit River System Cooperative)

---

.blue-text[
## Evaluation of status and trends for Skagit River Chinook salmon and steelhead
]

***

### .green-text[Funders:] Bureau of Indian Affairs, University of Washington

### .green-text[Status:] In development, expected to begin in June 2020

* ### Develop time series models to evaluate current status and trends in population censuses of Chinook salmon and steelhead

* ### Revise methods for estimating escapement from index stocks based on coded wire tagging of hatchery fish and test fisheries


---

.blue-text[
## Floodplains by Design
]

***

### Bob Carey (The Nature Conservancy)
### Jesse Israel (The Nature Conservancy)
### Lisa Nelson (WA Department of Ecology)
### Sara Breslow (UW EarthLab)

---

.blue-text[
## Floodplains by Design
]

***

### .green-text[Funders:] The Nature Conservancy, WA Department of Ecology

### .green-text[Status:] In development, expected to begin in Spring 2020

* ### Public-private partnership focused on integrating efforts to reduce flood risks and restore habitat across Washington State

* ### Improve resiliency of floodplains for the protection of human communities and ecosystem health while supporting agriculture, clean water, recreation, etc


---

class: black-back

